export {
  executeMarketingHistoryBackfill,
  planMarketingHistoryBackfill,
  ensureMarketingHistoryCatalog,
  MARKETING_HISTORY_CATALOG_PATH,
  DEFAULT_MARKETING_HISTORY_RETENTION_POLICY,
  compareLatestMarketingHistoryPeriods,
  discardMarketingFixtureEvidence,
  marketingHistoryCatalogSchema,
  marketingHistoryMetricSchema,
  marketingHistoryObservationSchema,
  marketingHistoryRetentionPolicySchema,
  queryMarketingHistory,
  queryMarketingHistoryCatalog,
  readMarketingHistoryReportWindow,
  readMarketingHistoryCatalog,
  rebuildMarketingHistoryCatalog,
  recordMarketingHistoryArtifact,
  type MarketingHistoryCatalog,
  type DiscardMarketingFixtureEvidenceOptions,
  type DiscardMarketingFixtureEvidenceResult,
  type MarketingHistoryBackfillPlan,
  type MarketingHistoryBackfillResult,
  type MarketingHistoryBackfillTarget,
  type MarketingHistoryBackfillWindow,
  type MarketingHistoryCoverage,
  type MarketingHistoryMetric,
  type MarketingHistoryObservation,
  type MarketingHistoryPeriodComparison,
  type MarketingHistoryPoint,
  type MarketingHistoryQuery,
  type MarketingHistoryQueryResult,
  type MarketingHistoryReportWindow,
  type MarketingHistoryReportWindowResult,
  type MarketingHistoryRetentionPolicy,
  type RecordMarketingHistoryResult,
} from './history/index.js';
export {
  MARKETING_GOOGLE_ADS_SCOPE,
  MARKETING_GOOGLE_ANALYTICS_SCOPE,
  MARKETING_GOOGLE_AUTH_SCOPES,
  MARKETING_GOOGLE_SEARCH_CONSOLE_SCOPE,
  MARKETING_GOOGLE_TAG_MANAGER_SCOPE,
  marketingGoogleConnectionReadyForProvider,
  requiredMarketingGoogleScope,
  type MarketingGoogleConnectionStatus,
} from './connections/google.js';
export {
  MARKETING_META_ADS_READ_SCOPE,
  MARKETING_META_MUTATION_SCOPES,
  MARKETING_META_READ_SCOPE_ALLOWLIST,
  assessMarketingMetaConnection,
  marketingMetaConnectionGrantSchema,
  marketingMetaConnectionReady,
  marketingMetaConnectionReadinessStateSchema,
  marketingMetaConnectionResourceSchema,
  marketingMetaConnectionServiceSchema,
  marketingMetaConnectionStatusSchema,
  marketingMetaResourceTypeSchema,
  type MarketingMetaConnectionAssessment,
  type MarketingMetaConnectionGrant,
  type MarketingMetaConnectionReadinessState,
  type MarketingMetaConnectionResource,
  type MarketingMetaConnectionService,
  type MarketingMetaConnectionServiceAssessment,
  type MarketingMetaConnectionStatus,
} from './connections/meta.js';
export {
  defineMarketingExecutionContext,
  marketingAttributionStoreSchema,
  marketingExecutionContextSchema,
  marketingEnvRefSchema,
  marketingEnvironmentSchema,
  marketingPathsSchema,
  marketingProviderSchema,
  marketingProviderAvailabilitySchema,
  type MarketingExecutionContext,
  type MarketingProviderAvailability,
} from './schema/execution-context.js';
export {
  marketingConsentCategorySchema,
  marketingConsentRequirementSchema,
  marketingEventDeliveryChannelSchema,
  marketingEventDeliveryExpectationSchema,
  marketingEventEmitterExpectationsSchema,
  marketingEventProviderMappingsSchema,
  marketingEventPropertySchema,
  marketingEventRegistrySchema,
  marketingEventSchema,
  marketingGa4EventMappingSchema,
  marketingGtmEventMappingSchema,
  marketingInternalAnalyticsMappingSchema,
  marketingLifecycleFamilySchema,
  marketingPropertyTypeSchema,
  type MarketingConsentCategory,
  type MarketingEvent,
  type MarketingEventDeliveryChannel,
  type MarketingEventDeliveryExpectation,
  type MarketingEventRegistry,
  type MarketingLifecycleFamily,
  migrateMarketingEventRegistryV1,
} from './schema/event-registry.js';
export {
  marketingConversionGoalSchema,
  marketingConversionProviderMappingsSchema,
  marketingConversionRegistrySchema,
  marketingConversionSchema,
  marketingGoogleAdsConversionMappingSchema,
  marketingMetaConversionMappingSchema,
  type MarketingConversion,
  type MarketingConversionGoal,
  type MarketingConversionRegistry,
} from './schema/conversion-registry.js';
export {
  marketingAdsPlanActionSchema,
  marketingAdsPlanActionTypeSchema,
  marketingAdsPlanArtifactSchema,
  marketingAdsPlanBidStrategySchema,
  marketingAdsPlanBudgetGuardrailSchema,
  marketingAdsPlanCandidateSchema,
  marketingGoogleAdsSearchSettingsSchema,
  marketingAdsPlanKeywordSchema,
  marketingAdsPlanNegativeKeywordSchema,
  marketingAdsPlanProviderSchema,
  marketingAdsPlanRiskSchema,
  marketingAdsPlanStatusSchema,
  marketingAdsPlanUtmSchema,
  type MarketingAdsPlanAction,
  type MarketingAdsPlanActionType,
  type MarketingAdsPlanArtifact,
  type MarketingAdsPlanBidStrategy,
  type MarketingAdsPlanBudgetGuardrail,
  type MarketingAdsPlanCandidate,
  type MarketingGoogleAdsSearchSettings,
  type MarketingAdsPlanKeyword,
  type MarketingAdsPlanNegativeKeyword,
  type MarketingAdsPlanProvider,
  type MarketingAdsPlanRisk,
  type MarketingAdsPlanStatus,
  type MarketingAdsPlanUtm,
} from './schema/ads-plan.js';
export {
  marketingCreativeApprovalStatusSchema,
  marketingCreativeAssetFileSchema,
  marketingCreativeAssetSchema,
  marketingCreativeAssetSourceSchema,
  marketingCreativeAssetTypeSchema,
  marketingCreativePolicyStatusSchema,
  marketingCreativeProviderSchema,
  type MarketingCreativeApprovalStatus,
  type MarketingCreativeAsset,
  type MarketingCreativeAssetFile,
  type MarketingCreativeAssetSource,
  type MarketingCreativeAssetType,
  type MarketingCreativePolicyStatus,
  type MarketingCreativeProvider,
} from './schema/ads-creative.js';
export {
  marketingAdsAssetLifecycleStatusSchema,
  marketingAdsAssetProviderRefSchema,
  marketingAdsAssetRegistrySchema,
  marketingAdsAssetSchema,
  marketingAdsAssetSourceFileSchema,
  marketingAdsAssetTypeSchema,
  marketingAdsAssetCreativePlanOperationSchema,
  marketingAdsAssetCreativePlanSchema,
  marketingMetaAdsPlacementSchema,
  marketingMetaAdsPlacementTargetingSchema,
  marketingAdsAssetUploadPlanOperationSchema,
  marketingAdsAssetUploadPlanSchema,
  marketingAdsAssetUploadConfirmationSchema,
  marketingAdsAssetUploadReceiptOperationSchema,
  marketingAdsAssetUploadReceiptSchema,
  marketingAdsAssetLiveUploadOperationReceiptSchema,
  marketingAdsAssetLiveUploadReceiptSchema,
  type MarketingAdsAsset,
  type MarketingAdsAssetCreativePlan,
  type MarketingAdsAssetLifecycleStatus,
  type MarketingAdsAssetLiveUploadReceipt,
  type MarketingAdsAssetProviderRef,
  type MarketingAdsAssetRegistry,
  type MarketingAdsAssetSourceFile,
  type MarketingAdsAssetType,
  type MarketingMetaAdsPlacement,
  type MarketingMetaAdsPlacementTargeting,
  type MarketingAdsAssetUploadConfirmation,
  type MarketingAdsAssetUploadPlan,
  type MarketingAdsAssetUploadReceipt,
} from './schema/ads-asset.js';
export {
  marketingAdsApplyConfirmationSchema,
  marketingAdsApplyApprovalTierSchema,
  marketingAdsApplyMutationIntentSchema,
  marketingAdsApplyOperationSchema,
  marketingAdsApplyPreviewSchema,
  marketingAdsApplyReceiptOperationSchema,
  marketingAdsApplyReceiptSchema,
  marketingAdsApplySafetySchema,
  marketingAdsLiveExecutionReceiptSchema,
  marketingAdsLiveExecutorModeSchema,
  marketingAdsLiveOperationReceiptSchema,
  type MarketingAdsApplyApprovalTier,
  type MarketingAdsApplyConfirmation,
  type MarketingAdsApplyMutationIntent,
  type MarketingAdsApplyOperation,
  type MarketingAdsApplyPreview,
  type MarketingAdsApplyReceipt,
  type MarketingAdsApplyReceiptActor,
  type MarketingAdsApplyReceiptOperation,
  type MarketingAdsApplyReceiptProviderAccount,
  type MarketingAdsApplySafety,
  type MarketingAdsLiveExecutionReceipt,
  type MarketingAdsLiveExecutorMode,
  type MarketingAdsLiveOperationReceipt,
} from './schema/ads-apply.js';
export {
  marketingRecommendationActionSchema,
  marketingRecommendationAlertSchema,
  marketingRecommendationAlertTypeSchema,
  marketingRecommendationApprovalTierSchema,
  marketingRecommendationArtifactSchema,
  marketingRecommendationDecisionReceiptSchema,
  marketingRecommendationDecisionSchema,
  marketingExperimentDecisionReceiptSchema,
  marketingExperimentDecisionSchema,
  marketingRecommendationExperimentSchema,
  marketingRecommendationConfidenceSchema,
  marketingRecommendationRiskSchema,
  marketingRecommendationSchema,
  marketingRecommendationSeveritySchema,
  type MarketingRecommendation,
  type MarketingRecommendationAction,
  type MarketingRecommendationAlert,
  type MarketingRecommendationAlertType,
  type MarketingRecommendationApprovalTier,
  type MarketingRecommendationArtifact,
  type MarketingRecommendationConfidence,
  type MarketingRecommendationDecision,
  type MarketingRecommendationDecisionReceipt,
  type MarketingExperimentDecision,
  type MarketingExperimentDecisionReceipt,
  type MarketingRecommendationExperiment,
  type MarketingRecommendationRisk,
  type MarketingRecommendationSeverity,
} from './schema/recommendation.js';
export {
  marketingResearchActionSchema,
  marketingResearchConfidenceSchema,
  marketingResearchDecisionSchema,
  marketingResearchEvidenceSchema,
  marketingResearchMemoryFileSchema,
  marketingResearchOpportunitySchema,
  marketingResearchPrioritySchema,
  marketingResearchRecordKindSchema,
  marketingResearchRecordSchema,
  marketingResearchRouteSchema,
  marketingResearchSourceKindSchema,
  marketingResearchStatusSchema,
  type MarketingResearchAction,
  type MarketingResearchDecision,
  type MarketingResearchEvidence,
  type MarketingResearchMemoryFile,
  type MarketingResearchOpportunity,
  type MarketingResearchPriority,
  type MarketingResearchRecord,
  type MarketingResearchStatus,
} from './schema/research-memory.js';
export {
  marketingAlertAcknowledgementReceiptSchema,
  type MarketingAlertAcknowledgementReceipt,
} from './schema/alert.js';
export {
  marketingProviderReportArtifactInputSchema,
  marketingProviderReportArtifactSchema,
  marketingCanonicalOutcomeArtifactInputSchema,
  marketingCanonicalOutcomeArtifactSchema,
  marketingCanonicalOutcomeRecordSchema,
  marketingCanonicalOutcomeReferenceSchema,
  marketingCanonicalOutcomeWindowSchema,
  marketingConfirmedConversionArtifactInputSchema,
  marketingConfirmedConversionArtifactSchema,
  marketingConfirmedConversionRecordSchema,
  marketingConfirmedConversionV1ArtifactSchema,
  marketingConfirmedConversionV1RecordSchema,
  marketingProviderReportRecordSchema,
  marketingProviderReportTypeSchema,
  marketingReportMetricsSchema,
  marketingReportProviderSchema,
  marketingReportRecordLevelSchema,
  marketingReportSourceSchema,
  marketingReportWindowSchema,
  marketingStrategyMapArtifactInputSchema,
  marketingStrategyMapArtifactSchema,
  marketingStrategyObjectKindSchema,
  marketingStrategyObjectSchema,
  marketingStrategyObjectStatusSchema,
  type MarketingProviderReportArtifact,
  type MarketingProviderReportArtifactInput,
  type MarketingCanonicalOutcomeArtifact,
  type MarketingCanonicalOutcomeArtifactInput,
  type MarketingCanonicalOutcomeRecord,
  type MarketingConfirmedConversionArtifact,
  type MarketingConfirmedConversionArtifactInput,
  type MarketingConfirmedConversionRecord,
  type MarketingConfirmedConversionV1Artifact,
  type MarketingProviderReportRecord,
  type MarketingProviderReportType,
  type MarketingReportMetrics,
  type MarketingReportProvider,
  type MarketingReportSource,
  type MarketingStrategyMapArtifact,
  type MarketingStrategyMapArtifactInput,
  type MarketingStrategyObject,
  type MarketingStrategyObjectKind,
  type MarketingStrategyObjectStatus,
} from './schema/report.js';
export {
  normalizeMarketingProviderReportInput,
  type MarketingProviderReportInputFormat,
  type NormalizeMarketingProviderReportInputOptions,
} from './reports/normalize-provider-input.js';
export {
  readMarketingProviderReportStatus,
  readLatestMarketingProviderReportArtifacts,
  writeMarketingProviderReportPull,
  type MarketingProviderPullOptions,
  type MarketingProviderPullResult,
  type MarketingProviderReportStatus,
  type MarketingProviderReportStatusOptions,
  type MarketingProviderReportStatusReport,
} from './reports/provider-pulls.js';
export {
  cacheMarketingConfirmedConversionArtifact,
  createMarketingCanonicalOutcomeReference,
  confirmedConversionCacheRoot,
  digestMarketingCanonicalOutcomeArtifact,
  latestMarketingCanonicalOutcomeRecords,
  migrateMarketingConfirmedConversionV1,
  readLatestMarketingConfirmedConversionArtifact,
  readMarketingConfirmedConversionStatus,
  writeMarketingConfirmedConversionPull,
  type MarketingConfirmedConversionPullOptions,
  type MarketingConfirmedConversionPullResult,
  type MarketingConfirmedConversionMigrationOptions,
  type MarketingConfirmedConversionStatus,
  type MarketingConfirmedConversionStatusOptions,
} from './reports/confirmed-conversions.js';
export {
  cacheMarketingStrategyMapArtifact,
  readLatestMarketingStrategyMapArtifact,
  readMarketingStrategyMapStatus,
  strategyMapCacheRoot,
  writeMarketingStrategyMapPull,
  type MarketingStrategyMapPullOptions,
  type MarketingStrategyMapPullResult,
  type MarketingStrategyMapStatus,
  type MarketingStrategyMapStatusOptions,
} from './reports/strategy-map.js';
export {
  buildMarketingStrategyObjectReport,
  type MarketingStrategyObjectJoin,
  type MarketingStrategyObjectReport,
} from './reports/strategy-object-report.js';
export {
  buildMarketingStatusReport,
  type MarketingStatusMode,
  type MarketingStatusOptions,
  type MarketingStatusReport,
} from './reports/status.js';
export {
  buildMarketingEvidenceStatus,
  type MarketingEvidenceCommand,
  type MarketingEvidenceProvider,
  type MarketingEvidenceProviderStatus,
  type MarketingEvidenceReportFamilyStatus,
  type MarketingEvidenceState,
  type MarketingEvidenceStatusOptions,
  type MarketingEvidenceStatusReport,
} from './reports/evidence-status.js';
export {
  summarizeConfirmedConversionMetrics,
  summarizeProviderArtifactMetrics,
  deriveMarketingMetrics,
  type MarketingDerivedMetrics,
} from './reports/metrics.js';
export {
  buildUnifiedMarketingReport,
  type MarketingUnifiedConversionTruth,
  type MarketingUnifiedMetricsSection,
  type MarketingUnifiedReport,
  type MarketingUnifiedReportOptions,
} from './reports/unified-report.js';
export {
  buildMarketingRecommendations,
  writeMarketingRecommendations,
  type MarketingRecommendationOptions,
  type MarketingRecommendationResult,
} from './recommendations/recommendations.js';
export {
  buildMarketingRecommendationDecisionReceipt,
  writeMarketingRecommendationDecisionReceipt,
  type MarketingRecommendationDecisionOptions,
  type MarketingRecommendationDecisionResult,
} from './recommendations/decision-receipts.js';
export {
  buildMarketingAlertAcknowledgementReceipt,
  writeMarketingAlertAcknowledgementReceipt,
  type MarketingAlertAcknowledgementOptions,
  type MarketingAlertAcknowledgementResult,
} from './alerts/acknowledgements.js';
export {
  buildMarketingExperimentDecisionReceipt,
  writeMarketingExperimentDecisionReceipt,
  type MarketingExperimentDecisionOptions,
  type MarketingExperimentDecisionResult,
} from './experiments/decisions.js';
export {
  marketingResearchRoot,
  readMarketingResearchMemoryFiles,
  readMarketingResearchStatus,
  type MarketingResearchStatusOptions,
  type MarketingResearchStatusSummary,
} from './research/memory.js';
export {
  writeMarketingProviderApiReportPull,
  type MarketingProviderApiPullOptions,
  type MarketingProviderApiPullResult,
} from './reports/provider-api-pulls.js';
export {
  buildMarketingScheduledReportingPlan,
  writeMarketingScheduledReportingPlan,
  type MarketingScheduledReportingCadence,
  type MarketingScheduledReportingJob,
  type MarketingScheduledReportingOptions,
  type MarketingScheduledReportingPlan,
  type MarketingScheduledReportingResult,
} from './reports/scheduled-reporting.js';
export {
  buildMarketingAdsDiffReport,
  type MarketingAdsDiffCandidate,
  type MarketingAdsDiffCheck,
  type MarketingAdsDiffCheckStatus,
  type MarketingAdsDiffOptions,
  type MarketingAdsDiffReport,
} from './ads/diff.js';
export {
  buildMarketingAdsAuditReport,
  writeMarketingAdsAuditReport,
  type MarketingAdsAuditAction,
  type MarketingAdsAuditOptions,
  type MarketingAdsAuditReport,
  type MarketingAdsAuditResult,
  type MarketingAdsAuditSection,
  type MarketingAdsAuditSectionStatus,
  type MarketingAdsAuditSeverity,
} from './ads/audit.js';
export {
  buildMarketingAdsOptimization,
  writeMarketingAdsOptimization,
  type MarketingAdsOptimizationOptions,
  type MarketingAdsOptimizationResult,
} from './ads/optimize.js';
export {
  buildMarketingAdsReadinessPlan,
  writeMarketingAdsReadinessPlan,
  type MarketingAdsOptimizationAction,
  type MarketingAdsReadinessArea,
  type MarketingAdsReadinessCheck,
  type MarketingAdsReadinessOptions,
  type MarketingAdsReadinessPlan,
  type MarketingAdsReadinessResult,
  type MarketingAdsReadinessStatus,
} from './ads/readiness.js';
export {
  buildMarketingAdsSearchTermsReport,
  writeMarketingAdsSearchTermsReport,
  type MarketingAdsSearchTermAction,
  type MarketingAdsSearchTermClassification,
  type MarketingAdsSearchTermsOptions,
  type MarketingAdsSearchTermsReport,
  type MarketingAdsSearchTermsResult,
} from './ads/search-terms.js';
export {
  buildMarketingNegativeKeywordReport,
  marketingNegativeKeywordEntrySchema,
  marketingNegativeKeywordRegistrySchema,
  writeMarketingNegativeKeywordReport,
  type MarketingNegativeKeywordCheck,
  type MarketingNegativeKeywordCoverage,
  type MarketingNegativeKeywordEntry,
  type MarketingNegativeKeywordOptions,
  type MarketingNegativeKeywordRegistry,
  type MarketingNegativeKeywordReport,
  type MarketingNegativeKeywordResult,
} from './ads/negative-keywords.js';
export {
  buildMarketingAdsCompetitorMonitorReport,
  marketingAdsCompetitorEntrySchema,
  marketingAdsCompetitorRegistrySchema,
  writeMarketingAdsCompetitorMonitorReport,
  type MarketingAdsCompetitorAction,
  type MarketingAdsCompetitorCheck,
  type MarketingAdsCompetitorEntry,
  type MarketingAdsCompetitorMonitorOptions,
  type MarketingAdsCompetitorMonitorReport,
  type MarketingAdsCompetitorMonitorResult,
  type MarketingAdsCompetitorRegistry,
  type MarketingAdsCompetitorSignal,
} from './ads/competitors.js';
export {
  buildMarketingAdsPlan,
  writeMarketingAdsPlan,
  type MarketingAdsPlanOptions,
  type MarketingAdsPlanResult,
} from './ads/plan.js';
export {
  buildMarketingAdsStatusReport,
  type MarketingAdsConversionMappingStatus,
  type MarketingAdsLatestArtifact,
  type MarketingAdsProvider,
  type MarketingAdsProviderStatus,
  type MarketingAdsStatusCheck,
  type MarketingAdsStatusCheckStatus,
  type MarketingAdsStatusOptions,
  type MarketingAdsStatusReport,
} from './ads/status.js';
export {
  creativeAssetsFromProviderArtifact,
  planMarketingCreativeAssets,
} from './ads/creative-assets.js';
export {
  buildMarketingAdsCreativeStatusReport,
  type MarketingAdsCreativeStatusCheck,
  type MarketingAdsCreativeStatusCheckStatus,
  type MarketingAdsCreativeStatusOptions,
  type MarketingAdsCreativeStatusReport,
} from './ads/creative-status.js';
export {
  buildMarketingAdsAssetReport,
  approveMarketingAdsAsset,
  archiveMarketingAdsAsset,
  importMarketingAdsAsset,
  readMarketingAdsAssetRegistry,
  writeMarketingAdsAssetUploadReceipt,
  writeMarketingAdsAssetCreativePlan,
  writeMarketingGoogleAdsCampaignAssetLinkReceipt,
  writeMarketingAdsAssetUploadPlan,
  readMarketingAdsAssetUploadPlan,
  type MarketingAdsAssetCheck,
  type MarketingAdsAssetCheckStatus,
  type MarketingAdsAssetImportOptions,
  type MarketingAdsAssetImportResult,
  type MarketingAdsAssetProviderUploader,
  type MarketingAdsAssetProviderUploaders,
  type MarketingAdsAssetProviderUploadOperation,
  type MarketingAdsAssetProviderUploadOptions,
  type MarketingAdsAssetProviderUploadResult,
  type MarketingAdsAssetProviderUploadSource,
  type MarketingAdsAssetCreativePlanOptions,
  type MarketingAdsAssetCreativePlanResult,
  type MarketingAdsAssetReport,
  type MarketingAdsAssetUpdateOptions,
  type MarketingAdsAssetUploadOptions,
  type MarketingAdsAssetUploadPlanOptions,
  type MarketingAdsAssetUploadPlanResult,
  type MarketingAdsAssetUploadResult,
  type MarketingGoogleAdsCampaignAssetLinkOptions,
  type MarketingGoogleAdsCampaignAssetLinkResult,
} from './ads/assets.js';
export {
  assertLiveAdsExecutorDisabled,
  executeMarketingAdsLiveOperation,
  type MarketingAdsExecutorMode,
  type MarketingAdsLiveExecutorOptions,
  type MarketingAdsLiveProviderExecutionOptions,
  type MarketingAdsLiveProviderExecutionResult,
  type MarketingAdsLiveProviderExecutor,
  type MarketingAdsLiveProviderExecutors,
  type MarketingAdsProviderExecutor,
  type MarketingAdsProviderExecutorResult,
} from './ads/executors.js';
export {
  buildMarketingAdsApplyPreview,
  writeMarketingAdsLiveApplyReceipt,
  writeMarketingAdsApplyPreview,
  type MarketingAdsLiveApplyOptions,
  type MarketingAdsLiveApplyResult,
  type MarketingAdsApplyOptions,
  type MarketingAdsApplyResult,
} from './ads/apply.js';
export {
  applyMarketingGoogleAdsGoals,
  buildMarketingGoogleAdsGoalPlan,
  writeMarketingGoogleAdsGoalPlan,
  type MarketingGoogleAdsGoalOperation,
  type MarketingGoogleAdsGoalOperationStatus,
  type MarketingGoogleAdsGoalPlan,
  type MarketingGoogleAdsGoalsOptions,
} from './goals/google-ads-goals.js';
export {
  loadMarketingRegistries,
  type LoadedMarketingRegistries,
  type LoadMarketingRegistryOptions,
} from './registry/load-registries.js';
export {
  validateMarketingRegistries,
  type MarketingRegistryCheck,
  type MarketingRegistryCheckStatus,
  type MarketingRegistryValidationOptions,
  type MarketingRegistryValidationReport,
} from './registry/validate-registries.js';
export {
  auditGoogleTagManagerManifest,
  type MarketingGtmAuditOptions,
} from './tracking/audit-gtm.js';
export { auditProviderConversionMappings } from './tracking/audit-provider-conversions.js';
export {
  auditMarketingTrackingSource,
  marketingTrackingCaptureEvidenceSchema,
  marketingTrackingCommerceEvidenceSchema,
  marketingTrackingConsentEvidenceSchema,
  marketingTrackingCustomerFieldEvidenceSchema,
  marketingTrackingDiagnosticEvidenceSchema,
  marketingTrackingEvidenceStateSchema,
  marketingTrackingIdentityDigestSchema,
  marketingTrackingObservationArtifactSchema,
  marketingTrackingObservationEmitterSchema,
  marketingTrackingObservationOutcomeSchema,
  marketingTrackingObservationSchema,
  marketingTrackingObservationWindowsSchema,
  marketingTrackingParameterEvidenceSchema,
  marketingTrackingParameterTypeSchema,
  marketingTrackingProviderReferenceSchema,
  marketingTrackingTransportFieldEvidenceSchema,
  marketingTrackingValidityStateSchema,
  migrateMarketingTrackingObservationArtifactV1,
  type MarketingTrackingEvidenceState,
  type MarketingTrackingObservation,
  type MarketingTrackingObservationArtifact,
  type MarketingTrackingAuditCheck,
  type MarketingTrackingAuditOptions,
  type MarketingTrackingAuditReport,
  type MarketingTrackingAuditStatus,
} from './tracking/audit-source.js';
export {
  deriveMarketingExecutionContext,
  type GrowthExecutionProjectContext,
} from './workspace/load-execution-context.js';
export type {
  FetchLike,
  MarketingProviderApiPullDriver,
  ProviderApiPullContext,
  ProviderApiPullInputFormat,
  ProviderApiPullOptions,
  ProviderApiPullPayload,
} from './providers/api-pull-types.js';
export { asArray, asRecord, optionalString } from './providers/report-utils.js';
export { normalizeGoogleAdsReport } from './providers/google-ads/reports.js';

export * from './ads/asset-provider.js';
