export type MarketingCliOptions = {
  accountId?: string;
  apiVersion?: string;
  authProfile?: string;
  cadence?: string;
  cwd?: string;
  config?: string;
  endDate?: string;
  dryRun?: boolean;
  experimentId?: string;
  followUpAction?: string;
  force?: boolean;
  input?: string;
  inputFormat?: 'normalized' | 'google-ads' | 'meta-ads' | 'ga4' | 'search-console';
  json?: boolean;
  limits?: string;
  approvalRef?: string;
  acknowledgedBy?: string;
  alertId?: string;
  decision?: 'accepted' | 'rejected' | 'ship' | 'iterate' | 'stop' | 'rerun' | 'inconclusive';
  decidedBy?: string;
  maxAgeDays?: string;
  maxPages?: string;
  metaAuthProfile?: string;
  pageSize?: string;
  provider?: string;
  recommendationId?: string;
  reason?: string;
  researchRoot?: string;
  report?: string;
  result?: 'won' | 'lost' | 'inconclusive';
  source?: 'api' | 'manual-export' | 'fixture';
  sourceRoot?: string[];
  out?: string;
  port?: string;
  spendSpikeAmount?: string;
  startDate?: string;
  targetCpa?: string;
  timeZone?: string;
  unified?: boolean;
  windowDays?: string;
};
