import type { MarketingAdsPlanProvider } from '@unisane/growth/marketing';
import type { MarketingProviderReportInputFormat } from '@unisane/growth/marketing';
import type { MarketingReportSource } from '@unisane/growth/marketing';

export type AdsCliOptions = {
  accountConfirm?: string;
  accountId?: string;
  api?: boolean;
  apiVersion?: string;
  approvalRef?: string;
  connection?: string;
  environment?: string;
  cwd?: string;
  currency?: string;
  dailyBudget?: string;
  dryRun?: boolean;
  endDate?: string;
  assetId?: string;
  campaignResource?: string;
  file?: string;
  fieldType?: string;
  input?: string;
  inputFormat?: MarketingProviderReportInputFormat;
  json?: boolean;
  license?: string;
  liveExecutor?: 'disabled' | 'api';
  maxAgeDays?: string;
  maxPages?: string;
  managerCustomerId?: string;
  name?: string;
  out?: string;
  owner?: string;
  pageSize?: string;
  placement?: string;
  plan?: string;
  policyNotes?: string;
  productionConfirm?: string;
  receipt?: string;
  operationConfirm?: string;
  provider?: MarketingAdsPlanProvider | 'all';
  report?: string;
  seoAdsPlan?: string;
  source?: MarketingReportSource;
  sourceRoot?: string[];
  startDate?: string;
  spendSpikeAmount?: string;
  sourceNotes?: string;
  strategyObjectId?: string;
  targetCpa?: string;
  timeZone?: string;
  type?: string;
  updateEnv?: boolean;
  yes?: boolean;
};
